name: 'Update Android Manifest package action'
description: 'Update the AndroidManifest.xml file'
author: 'damienaicheh'
inputs:
  android-manifest-path:
    description: 'Relative path for the AndroidManifest.xml file.'
    required: true
  package-name:
    description: 'Package value'
    required: true
  app-name:
    description: 'The application name'
    required: true
  print-file:
    description: 'Output the AndroidManifest.xml file in console'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'file'
  color: 'green'
